# See <https://github.com/greshake/i3status-rust>
# See man i3status-rs(1)

invert_scrolling = true

[theme]
theme = "semi-native"
[theme.overrides]
separator_fg = "#335544"
[icons]
icons = "awesome6"


###
### blocks
###

[[block]]
block = "net"
format = " $icon $device@{$ip | $ipv6} "

[[block]]
block = "backlight"
[[block.click]]
button = "left"
cmd = "lxrandr"

[[block]]
driver = "pulseaudio"
block = "sound"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
short = " $icon $timestamp.datetime(f:%R) "


[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
