require("which-key").register({
	name = "finder",
	["f"] = { "<cmd>Telescope find_files<cr>", "files" },
	["F"] = { "<cmd>Telescope find_files hidden=true ignore=true<cr>", "files-hidden" },
	["c"] = { "<cmd>Telescope quickfix<cr>", "quickfix" },
	["l"] = { "<cmd>Telescope loclist<cr>", "loclist" },
	["b"] = { "<cmd>Telescope buffers<cr>", "buffer" },
	["g"] = { "<cmd>Telescope live_grep<cr>", "live-grep" },
	["w"] = { "<cmd>Telescope grep_string<cr>", "<cword>" },
	["h"] = {
		name = "history",
		["f"] = { "<cmd>Telescope oldfiles<cr>", "file" },
		["c"] = { "<cmd>Telescope command_history<cr>", "command" },
		["/"] = { "<cmd>Telescope search_history<cr>", "search" },
	},
	["d"] = { "<cmd>Telescope diagnostics<cr>", "diagnostics" },
	["z"] = { "<cmd>Telescope zoxide list<cr>", "zoxide" },
	["/"] = { "<cmd>Telescope current_buffer_fuzzy_find<cr>", "search-text" },
	[":"] = { "<cmd>Telescope commands<cr>", "commands" },
	[" "] = { "<cmd>Telescope keymaps<cr>", "keymaps" },
	["."] = { "<cmd>Telescope builtin include_extensions=true<cr>", "finders" },
}, { mode = "n", silent = true, noremap = true, prefix = "<leader>f" })
