format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
\
$line_break\
\
$username@$hostname \
$status\
$character\
"""
right_format = """
$time \
$shlvl \
$cmd_duration \
$jobs\
"""
add_newline = false

#######################
# SECTION: MISC
#######################

[fill]
symbol = " "

#######################
# SECTION: right prompt
#######################

[time]
disabled = false
format = "[T](dimmed)[$time]($style)"
time_format = "%Y-%m-%d@%H:%M:%S"
style = "bold purple dimmed"
[cmd_duration]
disabled = false
min_time = 1
format = "[D](dimmed)[$duration]($style)"
style = "bold purple dimmed"
[jobs]
symbol_threshold = 0
number_threshold = 0
format = "[J](dimmed)[$number]($style)"
style = "bold purple dimmed"
[shlvl]
disabled = false
threshold = 0
format = "[L](dimmed)[$shlvl]($style)"
style = "bold purple dimmed"

#######################
# SECTION: left prompt
#######################

[status]
disabled = false
pipestatus = true
map_symbol = false
recognize_signal_code = true
format = "[\\[$signal_name$symbol$status\\]]($style)"
pipestatus_format = "$pipestatus ↦ [\\[$signal_name$symbol$status\\]]($style)"
pipestatus_separator = "|"
style = "blue"
symbol = "[✕](bold red)"
success_symbol = "[✓](bold green)"



[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"
style = "bold dimmed #00b33c"
[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_root = "bold red"
style_user = "bold yellow"
[directory]
truncate_to_repo = false
[character]
disabled = false
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[>](bold green)"


